BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[LogInTimes] (
    [id] NVARCHAR(1000) NOT NULL,
    [studentId] NVARCHAR(1000) NOT NULL,
    [logInTime] DATETIME2 NOT NULL CONSTRAINT [LogInTimes_logInTime_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [LogInTimes_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
